version: "3.7"
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/development/nginx/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "90:80"
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www

    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli/Dockerfile
        volumes:
            - ./:/var/www
            - composer:/root/.composer/cache